---
abstract: 'Bundle your shared dir into a tarball'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::DZil: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.034, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-ShareDir-Tarball
provides:
  Dist::Zilla::Plugin::ShareDir::Tarball:
    file: lib/Dist/Zilla/Plugin/ShareDir/Tarball.pm
    version: v0.6.0
requires:
  Archive::Tar: '0'
  Compress::Zlib: '0'
  Dist::Zilla::File::InMemory: '0'
  Dist::Zilla::Role::FileGatherer: '0'
  Dist::Zilla::Role::FileInjector: '0'
  Dist::Zilla::Role::FileMunger: '0'
  Dist::Zilla::Role::FilePruner: '0'
  Dist::Zilla::Role::ShareDir: '0'
  Moose: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dist-Zilla-Plugin-ShareDir-Tarball/issues
  homepage: https://github.com/yanick/Dist-Zilla-Plugin-ShareDir-Tarball
  repository: https://github.com/yanick/Dist-Zilla-Plugin-ShareDir-Tarball.git
version: 0.6.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Steven Haryanto <sharyanto@cpan.org>'
